Refactor with Value Types
hollar/ex_ach pull request #12
Opened 2018-03-06 21:31 UTC by bokay

Based on our discussion, we will follow the rules below:

1. A Builder pattern or a DSL are high-level interfaces that can be added later, if need be.
2. At a low level, we want to pass a FileHeader type 
3. Use Elixir primitives (like `Date` and `Time`)
4. Have types upfront in charge or coercion/cast, validation and documentation
```elixir
{:ok, t} | {:error, ...} = AccountNumber.new("12345")
```
This will give us also the opportunity to document
5. Validation can then be handled without a library like `Vex`, but with bare Elixir modules (eg. `Enum.count/1` or `String.length`).

*Reference:* https://github.com/hollar/ex_ach/pull/2#issuecomment-370916498

2018-03-08 20:36 UTC, bokay commented
@nicholasjhenry @frahugo  This PR is ready for review. As it's quite lengthy, I can walk you through the changes made, or if not, I'd suggest you to browse the project as a whole as it's a complete rewrite of the previous implementation.

2018-03-12 15:14 UTC, frahugo requested changes
Excellent job!  Few minor things to fix.  We can do that together.

2018-03-12 15:14 UTC, frahugo commented on README.md
> +alias ExAch.File.Header
Should be `ExAch.File`

2018-03-12 15:14 UTC, frahugo commented on README.md
> +alias ExAch.Batch.Header
Should be `ExAch.Batch`

2018-03-12 15:14 UTC, frahugo commented on README.md
> +  ExAch.Batch.Entry.new(
remove `ExAch`

2018-03-12 15:14 UTC, frahugo commented on README.md
> +  ExAch.Batch.Header.new(
remove `ExAch.`

2018-03-12 15:14 UTC, frahugo commented on README.md
> +  ExAch.File.Header.new(
remove `ExAch.`

2018-03-12 15:14 UTC, frahugo commented on README.md
> +{:ok, batch} = ExAch.Batch.new(header, entries)
Should be `ExAch.Batch.new(batch_header, entries)`

2018-03-12 15:14 UTC, frahugo commented on README.md
> +{:ok, ach} = ExAch.File.new(file_header, batches)
Maybe this instead?

```
{:ok, ach} = ExAch.File.new(file_header, [batch])
```

2018-03-12 15:14 UTC, frahugo commented on README.md
> +%ExAch.File{file_header: %FileHeader{}, batches: [%Batch]}
Maybe we can get rid of this line

2018-03-12 15:14 UTC, frahugo commented on README.md
> +ach = ExAch.new # => %ExAch.Ach{}
Are the next lines needed?

2018-03-12 15:14 UTC, frahugo commented on lib/ex_ach/batch/header/fields/standard_entry_class_code.ex
> +  use ExAch.Field, specifications: [type: :atom, inclusion: [:web, :ccd, :ppd, :ctx, :tel]]
I wonder if we should only include the codes the library is supporting.  Or we raise somewhere a "NotImplemented" exception.

2018-03-12 15:14 UTC, frahugo commented on lib/ex_ach/field_validator.ex
> +      {field_name, :type, "Must be alphanum"}
Maybe this? `Must be letters or digits`

2018-03-12 15:14 UTC, frahugo commented on lib/ex_ach/field_validator.ex
> +    |> Enum.reject(fn value -> value == nil end)
`Enum.reject(&is_nil/1)`

2018-03-12 15:14 UTC, frahugo commented on test/ex_ach/batch/entry_test.exs
> +      assert batch_entry.record_type_code == %RecordTypeCode{content: 6}
It might be better to hide the implementation of the content (maybe?):

`assert batch_entry.record_type_code == %RecordTypeCode.new(6)`

2018-03-12 15:14 UTC, frahugo commented on test/ex_ach/batch/header_validation_test.exs
> +    test "a valid value returns successfully" do
Remove `a ` and `an `

2018-03-12 15:14 UTC, frahugo commented on test/ex_ach/field_test.exs
> +    :dummy_field
I think we could remove this line by extracting the field_name logic into a `field_name` function in `Field`, and then add a test here: `assert Field.field_name(dummy) == :dummy_field`.

2018-03-12 15:14 UTC, frahugo commented on test/ex_ach/field_test.exs
> +  describe "validating content" do
Missing a test in the `describe` block

2018-03-12 15:14 UTC, frahugo commented on test/ex_ach/field_validator_test.exs
> +
Remove blank lines.  When the test has only 3 lines (or less), they should be grouped.

2018-03-12 15:14 UTC, frahugo commented on test/ex_ach/field_validator_test.exs
> +      assert errors == [{:field_name, :max_length, "Must be less than 3 character(s)"}]
The message should be "Must be less than or equal to 3 character(s)"

2018-03-12 15:14 UTC, frahugo commented on test/ex_ach/field_validator_test.exs
> +    test "a integer too long returns an error" do
Missing a test with less characters passed.

2018-03-12 15:14 UTC, frahugo commented on test/ex_ach/file/header_test.exs
> +      assert file_header.file_creation_time
`assert %FileCreationTime{} = file_header.file_creation_time`

2018-03-12 15:14 UTC, frahugo commented on test/ex_ach/file/header_test.exs
> +      # Optional fields passed by user
Wrong comment

2018-03-12 15:14 UTC, frahugo commented on test/ex_ach/file/header_test.exs
> +      assert file_header.immediate_destination_name == %ImmediateDestinationName{
Use the `new` function to hide content implementation.

2018-03-12 15:19 UTC, nicholasjhenry commented on lib/ex_ach/batch/entry/fields/dfi_account_number.ex
> +      type: :alpha_num_string,
@frahugo / @bokay seems like `alpha_numeric` would be an appropriate `type` name here.

2018-03-13 17:52 UTC, frahugo approved these changes

2018-03-13 17:52 UTC, merged